In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import matplotlib.font_manager as fm
font_name = fm.FontProperties(fname = "C:\\Windows\\Fonts\\malgun.ttf").get_name()
plt.rc("font", family =font_name)  #rc : 리모트컨트롤

import matplotlib as mlp
mlp.rcParams["axes.unicode_minus"]= False

### 아파트 전세

In [18]:
seoul_apt_2018_rent = pd.read_csv("C:\\hojun13\\Pythonwork\\Analysis\\Data\\data\\부동산 파일\\프로젝트\\2018 아파트 전세.csv", encoding='utf-8', index_col=0)
seoul_apt_2018_rent

    자치구별  1m^2 전용면적당 거래금액(만원)
0    강남구                660.0
1    강동구                474.0
2    강북구                338.0
3    강서구                408.0
4    관악구                369.0
5    광진구                538.0
6    구로구                360.0
7    금천구                335.0
8    노원구                297.0
9    도봉구                276.0
10  동대문구                408.0
11   동작구                502.0
12   마포구                512.0
13  서대문구                436.0
14   서초구                648.0
15   성동구                546.0
16   성북구                410.0
17   송파구                580.0
18   양천구                496.0
19  영등포구                448.0
20   용산구                513.0
21   은평구                371.0
22   종로구                426.0
23    중구                485.0
24   중랑구                304.0
25    평균                446.0

In [19]:
seoul_apt_2019_rent = pd.read_csv("C:\\hojun13\\Pythonwork\\Analysis\\Data\\data\\부동산 파일\\프로젝트\\2019 아파트 전세.csv", encoding='utf-8', index_col=0)
seoul_apt_2019_rent

    자치구별  1m^2 전용면적당 거래금액(만원)
0    강남구                681.0
1    강동구                474.0
2    강북구                341.0
3    강서구                442.0
4    관악구                380.0
5    광진구                545.0
6    구로구                361.0
7    금천구                346.0
8    노원구                304.0
9    도봉구                282.0
10  동대문구                423.0
11   동작구                499.0
12   마포구                536.0
13  서대문구                465.0
14   서초구                643.0
15   성동구                562.0
16   성북구                418.0
17   송파구                580.0
18   양천구                485.0
19  영등포구                481.0
20   용산구                536.0
21   은평구                398.0
22   종로구                544.0
23    중구                461.0
24   중랑구                374.0
25    평균                462.0

In [20]:
seoul_apt_2020_rent = pd.read_csv("C:\\hojun13\\Pythonwork\\Analysis\\Data\\data\\부동산 파일\\프로젝트\\2020 아파트 전세.csv", encoding='utf-8', index_col=0)
seoul_apt_2020_rent

    자치구별  1m^2 전용면적당 거래금액(만원)
0    강남구                787.0
1    강동구                519.0
2    강북구                396.0
3    강서구                454.0
4    관악구                410.0
5    광진구                604.0
6    구로구                374.0
7    금천구                412.0
8    노원구                335.0
9    도봉구                317.0
10  동대문구                479.0
11   동작구                573.0
12   마포구                524.0
13  서대문구                502.0
14   서초구                765.0
15   성동구                623.0
16   성북구                465.0
17   송파구                651.0
18   양천구                529.0
19  영등포구                509.0
20   용산구                583.0
21   은평구                441.0
22   종로구                487.0
23    중구                555.0
24   중랑구                394.0
25    평균                508.0

In [21]:
seoul_apt_2021_rent = pd.read_csv("C:\\hojun13\\Pythonwork\\Analysis\\Data\\data\\부동산 파일\\프로젝트\\2021 아파트 전세.csv", encoding='utf-8', index_col=0)
seoul_apt_2021_rent

    자치구별  1m^2 전용면적당 거래금액(만원)
0    강남구                833.0
1    강동구                520.0
2    강북구                393.0
3    강서구                470.0
4    관악구                459.0
5    광진구                667.0
6    구로구                364.0
7    금천구                403.0
8    노원구                367.0
9    도봉구                354.0
10  동대문구                516.0
11   동작구                635.0
12   마포구                591.0
13  서대문구                537.0
14   서초구                804.0
15   성동구                665.0
16   성북구                500.0
17   송파구                673.0
18   양천구                535.0
19  영등포구                555.0
20   용산구                630.0
21   은평구                448.0
22   종로구                577.0
23    중구                574.0
24   중랑구                423.0
25    평균                540.0

In [22]:
seoul_apt_2022_rent = pd.read_csv("C:\\hojun13\\Pythonwork\\Analysis\\Data\\data\\부동산 파일\\프로젝트\\2022 아파트 전세.csv", encoding='utf-8', index_col=0)
seoul_apt_2022_rent

    자치구별  1m^2 전용면적당 거래금액(만원)
0    강남구                795.0
1    강동구                545.0
2    강북구                376.0
3    강서구                464.0
4    관악구                441.0
5    광진구                641.0
6    구로구                370.0
7    금천구                438.0
8    노원구                347.0
9    도봉구                323.0
10  동대문구                503.0
11   동작구                586.0
12   마포구                554.0
13  서대문구                512.0
14   서초구                822.0
15   성동구                658.0
16   성북구                475.0
17   송파구                662.0
18   양천구                544.0
19  영등포구                556.0
20   용산구                573.0
21   은평구                462.0
22   종로구                518.0
23    중구                545.0
24   중랑구                380.0
25    평균                524.0

### 아파트 매매가

In [23]:
seoul_apt_2018_buysell = pd.read_csv("C:\\hojun13\\Pythonwork\\Analysis\\Data\\data\\부동산 파일\\프로젝트\\2018 아파트 매매가.csv", encoding='utf-8', index_col=0)
seoul_apt_2018_buysell

    자치구별  1m^2 전용면적당 거래금액(만원)
0    강남구               1702.0
1    강동구                858.0
2    강북구                563.0
3    강서구                728.0
4    관악구                642.0
5    광진구                943.0
6    구로구                595.0
7    금천구                516.0
8    노원구                601.0
9    도봉구                504.0
10  동대문구                693.0
11   동작구                880.0
12   마포구                989.0
13  서대문구                727.0
14   서초구               1461.0
15   성동구               1048.0
16   성북구                629.0
17   송파구               1201.0
18   양천구                811.0
19  영등포구                845.0
20   용산구               1200.0
21   은평구                627.0
22   종로구                764.0
23    중구                871.0
24   중랑구                541.0
25    평균                838.0

In [24]:
seoul_apt_2019_buysell = pd.read_csv("C:\\hojun13\\Pythonwork\\Analysis\\Data\\data\\부동산 파일\\프로젝트\\2019 아파트 매매가.csv", encoding='utf-8', index_col=0)
seoul_apt_2019_buysell

    자치구별  1m^2 전용면적당 거래금액(만원)
0    강남구               2051.0
1    강동구               1007.0
2    강북구                665.0
3    강서구                852.0
4    관악구                757.0
5    광진구               1105.0
6    구로구                707.0
7    금천구                619.0
8    노원구                703.0
9    도봉구                594.0
10  동대문구                840.0
11   동작구               1066.0
12   마포구               1221.0
13  서대문구                922.0
14   서초구               1755.0
15   성동구               1245.0
16   성북구                771.0
17   송파구               1440.0
18   양천구               1038.0
19  영등포구               1039.0
20   용산구               1463.0
21   은평구                729.0
22   종로구               1015.0
23    중구               1024.0
24   중랑구                660.0
25    평균               1012.0

In [25]:
seoul_apt_2020_buysell = pd.read_csv("C:\\hojun13\\Pythonwork\\Analysis\\Data\\data\\부동산 파일\\프로젝트\\2020 아파트 매매가.csv", encoding='utf-8', index_col=0)
seoul_apt_2020_buysell

    자치구별  1m^2 전용면적당 거래금액(만원)
0    강남구               2117.0
1    강동구               1170.0
2    강북구                771.0
3    강서구                964.0
4    관악구                871.0
5    광진구               1291.0
6    구로구                769.0
7    금천구                739.0
8    노원구                844.0
9    도봉구                675.0
10  동대문구                995.0
11   동작구               1230.0
12   마포구               1344.0
13  서대문구               1038.0
14   서초구               1913.0
15   성동구               1471.0
16   성북구                914.0
17   송파구               1601.0
18   양천구               1143.0
19  영등포구               1180.0
20   용산구               1594.0
21   은평구                827.0
22   종로구               1034.0
23    중구               1138.0
24   중랑구                760.0
25    평균               1136.0

In [26]:
seoul_apt_2021_buysell = pd.read_csv("C:\\hojun13\\Pythonwork\\Analysis\\Data\\data\\부동산 파일\\프로젝트\\2021 아파트 매매가.csv", encoding='utf-8', index_col=0)
seoul_apt_2021_buysell

    자치구별  1m^2 전용면적당 거래금액(만원)
0    강남구               2351.0
1    강동구               1437.0
2    강북구                939.0
3    강서구               1175.0
4    관악구               1089.0
5    광진구               1517.0
6    구로구                945.0
7    금천구                914.0
8    노원구               1116.0
9    도봉구                899.0
10  동대문구               1174.0
11   동작구               1670.0
12   마포구               1568.0
13  서대문구               1256.0
14   서초구               2208.0
15   성동구               1806.0
16   성북구               1144.0
17   송파구               1983.0
18   양천구               1353.0
19  영등포구               1378.0
20   용산구               1903.0
21   은평구               1042.0
22   종로구               1239.0
23    중구               1285.0
24   중랑구                969.0
25    평균               1374.0

In [27]:
seoul_apt_2022_buysell = pd.read_csv("C:\\hojun13\\Pythonwork\\Analysis\\Data\\data\\부동산 파일\\프로젝트\\2022 아파트 매매가.csv", encoding='utf-8', index_col=0)
seoul_apt_2022_buysell

    자치구별  1m^2 전용면적당 거래금액(만원)
0    강남구               2296.0
1    강동구               1322.0
2    강북구                942.0
3    강서구               1036.0
4    관악구               1045.0
5    광진구               1424.0
6    구로구                881.0
7    금천구               1014.0
8    노원구               1116.0
9    도봉구                890.0
10  동대문구               1108.0
11   동작구               1422.0
12   마포구               1567.0
13  서대문구               1219.0
14   서초구               2328.0
15   성동구               1841.0
16   성북구               1129.0
17   송파구               1965.0
18   양천구               1310.0
19  영등포구               1220.0
20   용산구               1986.0
21   은평구               1056.0
22   종로구               1175.0
23    중구               1217.0
24   중랑구                994.0
25    평균               1340.0

### 서울시 카페의 개수

In [10]:
seoul_cafe = pd.read_csv("C:\\hojun13\\Pythonwork\\Analysis\\Data\\data\\부동산 파일\\프로젝트\\연도별 서울 카페수.csv", encoding='utf-8', index_col=0)
seoul_cafe

    자치구별  2018카페수  2019카페수  2020카페수  2021카페수  2022카페수
0    구로구   407.00   414.00   459.00   474.00   488.00
1    서초구   949.00   974.00  1005.00  1004.00  1012.00
2   영등포구   799.00   844.00   864.00   916.00   899.00
3   서대문구   492.00   525.00   522.00   496.00   496.00
4    강남구  1679.00  1794.00  1834.00  1873.00  1883.00
5     중구  1072.00  1135.00  1149.00  1148.00  1166.00
6    송파구   445.00   476.00   585.00   692.00   792.00
7    종로구   877.00   896.00   862.00   850.00   873.00
8    마포구   943.00   851.00   755.00   906.00   930.00
9    성북구   433.00   455.00   492.00   524.00   559.00
10  동대문구   395.00   408.00   424.00   427.00   403.00
11   용산구   391.00   422.00   444.00   449.00   480.00
12   중랑구   247.00   296.00   329.00   367.00   377.00
13   강북구   211.00   221.00   243.00   251.00   239.00
14   동작구   416.00   439.00   432.00   453.00   465.00
15   은평구   387.00   368.00   400.00   408.00   379.00
16   강서구   748.00   842.00   907.00   984.00  1004.00
17   강동구   416.00   471.00   517.00   579.00   608.00
18   도봉구   229.00   249.00   273.00   281.00   275.00
19   금천구   324.00   339.00   375.00   400.00   423.00
20   양천구   357.00   392.00   415.00   425.00   442.00
21   관악구   479.00   527.00   559.00   593.00   594.00
22   노원구   433.00   475.00   484.00   523.00   546.00
23   광진구   374.00   443.00   503.00   551.00   580.00
24   성동구   344.00   383.00   422.00   437.00   439.00
25    평균   553.88   585.56   610.16   640.44   654.08

### 2018~2022 인구 이동

In [15]:
seoul_pop_2018 = pd.read_csv("C:\\hojun13\\Pythonwork\\Analysis\\Data\\data\\부동산 파일\\프로젝트\\2018인구이동.csv", encoding='utf-8', index_col=0)
seoul_pop_2018

    자치구별  2018 총전입  2018 총전출  2018 순이동  2018 인구이동률(%)
1     평균   1439707   1549937   -110230           -3.7
2    종로구     23187     24798     -1611           -3.4
3     중구     20771     20873      -102           -0.2
4    용산구     37339     37801      -462           -0.6
5    성동구     51358     49012      2346            2.3
6    광진구     55728     58774     -3046           -2.7
7   동대문구     54899     57605     -2706           -2.4
8    중랑구     54168     59616     -5448           -4.8
9    성북구     57147     65477     -8330           -6.8
10   강북구     40941     45800     -4859           -5.6
11   도봉구     39518     44213     -4695           -5.6
12   노원구     61867     72748    -10881           -8.1
13   은평구     67489     71519     -4030           -2.9
14  서대문구     45861     48484     -2623           -2.8
15   마포구     60227     61071      -844           -0.7
16   양천구     54579     62414     -7835           -6.7
17   강서구     83699     90281     -6582           -3.8
18   구로구     51108     58543     -7435           -6.8
19   금천구     33794     35508     -1714           -2.5
20  영등포구     59862     62108     -2246           -1.8
21   동작구     65099     66105     -1006           -0.8
22   관악구     94403     96477     -2074           -1.1
23   서초구     74658     83489     -8831           -5.6
24   강남구     91611    106802    -15191           -7.7
25   송파구    101060    101486      -426           -0.2
26   강동구     59334     68933     -9599           -7.5

In [14]:
seoul_pop_2019 = pd.read_csv("C:\\hojun13\\Pythonwork\\Analysis\\Data\\data\\부동산 파일\\프로젝트\\2019인구이동.csv", encoding='utf-8', index_col=0)
seoul_pop_2019

    자치구별  2019 총전입  2019 총전출  2019 순이동  2019 인구이동률(%)
1     평균   1426493   1476081    -49588           -1.7
2    종로구     22271     23945     -1674           -3.6
3     중구     19623     19384       239            0.6
4    용산구     35099     35673      -574           -0.8
5    성동구     39922     48102     -8180           -9.3
6    광진구     52191     57088     -4897           -4.5
7   동대문구     51660     53660     -2000           -1.9
8    중랑구     49446     55932     -6486           -6.2
9    성북구     67841     61169      6672            5.2
10   강북구     38046     42622     -4576           -5.7
11   도봉구     35445     41225     -5780           -7.5
12   노원구     57183     68095    -10912           -8.7
13   은평구     69399     72721     -3322           -2.3
14  서대문구     45729     46677      -948           -1.0
15   마포구     57766     59573     -1807           -1.5
16   양천구     50256     56733     -6477           -6.1
17   강서구     78518     85057     -6539           -4.0
18   구로구     54791     53666      1125            1.0
19   금천구     32416     33728     -1312           -2.0
20  영등포구     56874     58253     -1379           -1.2
21   동작구     61168     62047      -879           -0.7
22   관악구     93583     95788     -2205           -1.2
23   서초구     63335     67634     -4299           -3.3
24   강남구     95557     93716      1841            1.0
25   송파구    123273    116301      6972            2.9
26   강동구     75101     67292      7809            5.5

In [13]:
seoul_pop_2020 = pd.read_csv("C:\\hojun13\\Pythonwork\\Analysis\\Data\\data\\부동산 파일\\프로젝트\\2020인구이동.csv", encoding='utf-8', index_col=0)
seoul_pop_2020

    자치구별  2020 총전입  2020 총전출  2020 순이동  2020 인구이동률(%)
1     평균   1578127   1642977    -64850           -2.0
2    종로구     23632     25254     -1622           -3.3
3     중구     20777     21733      -956           -2.2
4    용산구     40282     38985      1297            1.6
5    성동구     45153     53096     -7943           -8.1
6    광진구     55926     60703     -4777           -4.1
7   동대문구     54908     58135     -3227           -2.9
8    중랑구     60214     62212     -1998           -1.6
9    성북구     62953     68231     -5278           -4.0
10   강북구     41625     46656     -5031           -5.7
11   도봉구     40435     47892     -7457           -8.4
12   노원구     68176     77707     -9531           -6.5
13   은평구     76364     76165       199            0.1
14  서대문구     56504     53579      2925            2.7
15   마포구     66215     68667     -2452           -1.8
16   양천구     64081     68021     -3940           -3.0
17   강서구     87198     99573    -12375           -6.6
18   구로구     60885     64024     -3139           -2.5
19   금천구     35753     36963     -1210           -1.7
20  영등포구     79309     68526     10783            7.3
21   동작구     64496     69650     -5154           -3.8
22   관악구     98301    103226     -4925           -2.4
23   서초구     71250     77669     -6419           -4.3
24   강남구     95325    101582     -6257           -3.2
25   송파구    106928    116457     -9529           -4.3
26   강동구    101437     78271     23166           12.9

In [16]:
seoul_pop_2021 = pd.read_csv("C:\\hojun13\\Pythonwork\\Analysis\\Data\\data\\부동산 파일\\프로젝트\\2021인구이동.csv", encoding='utf-8', index_col=0)
seoul_pop_2021

    자치구별  2021 총전입  2021 총전출  2021 순이동  2021 인구이동률(%)
1     평균   1418187   1524430   -106243           -3.6
2    종로구     22204     24428     -2224           -4.8
3     중구     19917     21126     -1209           -2.9
4    용산구     36011     39572     -3561           -4.7
5    성동구     39831     46075     -6244           -7.3
6    광진구     51522     56750     -5228           -4.8
7   동대문구     48955     51031     -2076           -2.1
8    중랑구     52867     57957     -5090           -4.6
9    성북구     59054     62394     -3340           -2.8
10   강북구     37057     42961     -5904           -7.4
11   도봉구     36895     42682     -5787           -7.3
12   노원구     58736     68473     -9737           -7.7
13   은평구     63269     66951     -3682           -2.8
14  서대문구     42484     47061     -4577           -5.1
15   마포구     61543     62124      -581           -0.5
16   양천구     54952     60442     -5490           -4.8
17   강서구     87269     91368     -4099           -2.3
18   구로구     48170     54880     -6710           -6.5
19   금천구     35663     35047       616            0.9
20  영등포구     60565     61108      -543           -0.4
21   동작구     64257     68311     -4054           -3.1
22   관악구     89756     95711     -5955           -3.2
23   서초구     70064     81777    -11713           -7.7
24   강남구     94082     98106     -4024           -2.1
25   송파구    105181    113651     -8470           -3.9
26   강동구     77883     74444      3439            2.3

In [17]:
seoul_pop_2022 = pd.read_csv("C:\\hojun13\\Pythonwork\\Analysis\\Data\\data\\부동산 파일\\프로젝트\\2022인구이동.csv", encoding='utf-8', index_col=0)
seoul_pop_2022

    자치구별  2022 총전입  2022 총전출  2022 순이동  2022 인구이동률(%)
1     평균   1201527   1236867    -35340           -1.4
2    종로구     19123     20556     -1433           -3.6
3     중구     16738     17465      -727           -2.1
4    용산구     31046     32325     -1279           -2.0
5    성동구     34138     38153     -4015           -5.6
6    광진구     45983     47193     -1210           -1.3
7   동대문구     44531     43365      1166            1.3
8    중랑구     45183     45343      -160           -0.2
9    성북구     52764     50725      2039            2.0
10   강북구     31243     34364     -3121           -4.8
11   도봉구     28791     32358     -3567           -5.8
12   노원구     48607     53482     -4875           -4.8
13   은평구     55986     59509     -3523           -3.1
14  서대문구     43478     39904      3574            4.3
15   마포구     49721     52169     -2448           -2.4
16   양천구     44539     49292     -4753           -5.1
17   강서구     70228     73672     -3444           -2.4
18   구로구     44870     45359      -489           -0.5
19   금천구     30153     30370      -217           -0.4
20  영등포구     53661     53953      -292           -0.3
21   동작구     53359     56607     -3248           -3.0
22   관악구     87212     83760      3452            2.0
23   서초구     51077     57143     -6066           -5.6
24   강남구     75316     76819     -1503           -1.0
25   송파구     88263     86137      2126            1.2
26   강동구     55517     56844     -1327           -1.2

### 서울시 버스 정류장 수

In [12]:
seoul_bus = pd.read_csv("C:\\hojun13\\Pythonwork\\Analysis\\Data\\data\\부동산 파일\\프로젝트\\연도별 서울 정류장수.csv", encoding='utf-8', index_col=0)
seoul_bus

    자치구별  2018정류장수  2019정류장수  2020정류장수  2021정류장수  2022정류장수
0    강남구     534.0     548.0     545.0    520.00    823.00
1    강동구     349.0     385.0     383.0    365.00    573.00
2    강북구     460.0     448.0     415.0    409.00    454.00
3    강서구     576.0     603.0     611.0    569.00    801.00
4    관악구     485.0     485.0     470.0    467.00    638.00
5    광진구     286.0     292.0     288.0    270.00    380.00
6    구로구     478.0     513.0     510.0    497.00    720.00
7    금천구     342.0     362.0     357.0    342.00    540.00
8    노원구     537.0     544.0     538.0    527.00    736.00
9    도봉구     386.0     391.0     366.0    358.00    448.00
10  동대문구     318.0     319.0     311.0    303.00    408.00
11   동작구     460.0     447.0     440.0    437.00    545.00
12   마포구     569.0     568.0     570.0    563.00    764.00
13  서대문구     444.0     446.0     457.0    454.00    542.00
14   서초구     648.0     649.0     638.0    605.00    962.00
15   성동구     439.0     442.0     433.0    445.00    502.00
16   성북구     611.0     604.0     599.0    601.00    670.00
17   송파구     413.0     429.0     440.0    414.00    716.00
18   양천구     363.0     365.0     320.0    317.00    491.00
19  영등포구     491.0     504.0     494.0    466.00    679.00
20   용산구     349.0     344.0     327.0    328.00    441.00
21   은평구     499.0     511.0     501.0    497.00    725.00
22   종로구     382.0     375.0     374.0    369.00    472.00
23    중구     207.0     211.0     241.0    200.00    309.00
24   중랑구     379.0     380.0     382.0    380.00    479.00
25    평균     440.2     446.6     440.4    428.12    592.72

### 서울시 편의점 수

In [11]:
seoul_con = pd.read_csv("C:\\hojun13\\Pythonwork\\Analysis\\Data\\data\\부동산 파일\\프로젝트\\연도별 서울 편의점수.csv", encoding='utf-8', index_col=0)
seoul_con

    자치구별  2018편의점수  2019편의점수  2020편의점수  2021편의점수  2022편의점수
0    서초구    298.00     314.0     321.0    317.00    323.00
1    강남구    558.00     597.0     606.0    615.00    627.00
2    동작구    118.00     141.0     147.0    161.00    172.00
3    송파구    108.00     123.0     160.0    208.00    243.00
4    광진구    137.00     181.0     200.0    220.00    233.00
5    용산구    105.00     118.0     129.0    130.00    135.00
6   동대문구    154.00     188.0     188.0    204.00    221.00
7    마포구    219.00     202.0     183.0    221.00    233.00
8    노원구    139.00     153.0     165.0    189.00    197.00
9   영등포구    263.00     303.0     326.0    330.00    322.00
10   강서구    209.00     260.0     279.0    282.00    308.00
11   성북구    121.00     148.0     165.0    180.00    199.00
12   성동구    108.00     123.0     126.0    144.00    165.00
13   종로구     87.00      94.0      84.0     85.00     87.00
14    중구    198.00     215.0     213.0    212.00    217.00
15   은평구    135.00     126.0     148.0    166.00    169.00
16   강북구     90.00     107.0     122.0    132.00    136.00
17   강동구    220.00     254.0     268.0    280.00    286.00
18   구로구    156.00     184.0     207.0    229.00    254.00
19   양천구    147.00     174.0     186.0    198.00    203.00
20   관악구    250.00     278.0     265.0    285.00    298.00
21   금천구    133.00     162.0     173.0    203.00    207.00
22   도봉구    113.00     129.0     137.0    149.00    156.00
23   중랑구    144.00     186.0     196.0    223.00    233.00
24  서대문구    124.00     160.0     191.0    201.00    208.00
25    평균    173.36     196.8     207.4    222.56    233.28

### 서울시 공원 수

### 서울시 학교 수

### 서울시 의료기관 수

### 서울시 지하철 수

### 금리 표

In [33]:
seoul_rate = pd.read_csv("C:\\hojun13\\Pythonwork\\Analysis\\Data\\data\\부동산 파일\\프로젝트\\연도별 금리 최종본.csv", encoding='utf-8', index_col=0)
seoul_rate

     연도  기준금리  기준금리 변동률(%)
0  2022  3.25        225.0
1  2021  1.00        100.0
2  2020  0.50        -60.0
3  2019  1.25        -28.6
4  2018  1.75         16.7

### 연도별 물가 지수 표

In [32]:
seoul_price = pd.read_csv("C:\\hojun13\\Pythonwork\\Analysis\\Data\\data\\부동산 파일\\프로젝트\\연도별 물가.csv", encoding='utf-8', index_col=0)
seoul_price

     연도     물가지수  물가지수 상승률(%)
0  2022  107.710          5.1
1  2021  102.500          2.5
2  2020  100.000          0.5
3  2019   99.466          0.4
4  2018   99.086          1.5

### 연도별 GDP

In [31]:
seoul_GDP = pd.read_csv("C:\\hojun13\\Pythonwork\\Analysis\\Data\\data\\부동산 파일\\프로젝트\\연도별 GDP 최종본.csv", encoding='utf-8', index_col=0)
seoul_GDP

     연도   GDP(십억원)  GDP 변동률(%)
0  2022  2150575.8         3.8
1  2021  2071658.0         6.7
2  2020  1940726.2         0.8
3  2019  1924498.1         1.4
4  2018  1898192.6         3.4

### 서울시 아파트 관심도

In [34]:
seoul_interest = pd.read_csv("C:\\hojun13\\Pythonwork\\Analysis\\Data\\data\\부동산 파일\\프로젝트\\서울시 아파트 관심도.csv", encoding='utf-8', index_col=0)
seoul_interest

          월  서울시 아파트
0   2017-01       57
1   2017-02       58
2   2017-03        0
3   2017-04       73
4   2017-05       75
..      ...      ...
71  2022-12       51
72  2023-01       33
73  2023-02       68
74  2023-03       54
75  2023-04       50

[76 rows x 2 columns]